export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST'
export const RECEIVE_COIN_LIST = 'RECEIVE_COIN_LIST'
export const ERROR_FETCHING_COIN_LIST = 'ERROR_FETCHING_COIN_LIST'

// workbench
export const ADD_WORKBENCH = 'ADD_WORKBENCH'
export const REMOVE_WORKBENCH = 'REMOVE_WORKBENCH'