//coinList
export const FETCHING_COIN_LIST = 'FETCHING_COIN_LIST'
export const RECEIVE_COIN_LIST = 'RECEIVE_COIN_LIST'
export const ERROR_FETCHING_COIN_LIST = 'ERROR_FETCHING_COIN_LIST'

// workbench
export const ADD_WORKBENCH = 'ADD_WORKBENCH'
export const REMOVE_WORKBENCH = 'REMOVE_WORKBENCH'

//coinValue
export const ERROR_FETCHING_COIN_VALUE = 'ERROR_FETCHING_COIN_VALUE'
export const FETCHING_COIN_VALUE = 'FETCHING_COIN_VALUE'
export const RECEIVE_COIN_VALUE = 'RECEIVE_COIN_VALUE'

//coinSnapshot
export const ERROR_FETCHING_COIN_SNAPSHOT = 'ERROR_FETCHING_COIN_SNAPSHOT'
export const FETCHING_COIN_SNAPSHOT = 'FETCHING_COIN_SNAPSHOT'
export const RECEIVE_COIN_SNAPSHOT = 'RECEIVE_COIN_SNAPSHOT'
